---
- name: init | started and enabled basic services
  service: name={{ item }} state=started enabled=yes
  with_items: [ "crond", "rsyslog" ]

- name: init | stopped and disbaled unnecessary services
  service: name={{ item }} state=stopped enabled=no
  with_items: [ "cups", "postfix", "rpcbind", "portreserve" ]
  ignore_errors: yes
