---
- name: init | update centos to latest version
  yum: name="*" state=latest

#- name: init | mkdir old repo backup dir
#  file: path=/etc/yum.repos.d/bak state=directory mode=0755
#
#- name: init | test CentOS-Base.repo is exists
#  stat: path=/etc/yum.repos.d/CentOS-Base.repo
#  register: centos_base_repo
#
#- name: init | backup old centos repo
#  shell: mv -v CentOS-*.repo bak
#  args:
#    chdir: "/etc/yum.repos.d"
#  when: centos_base_repo.stat.exists == True
