---
- hosts: "{{ hosts }}"
  become_method: sudo
  become: yes

  vars_prompt:
    - name: "iptables_profile"
      prompt: "please input your iptables profile name"
      default: "iptables-init"
      private: no

  tasks:
    - include: tasks/iptables.yml
