---
- hosts: "{{ hosts }}"
  become_method: sudo
  become: yes

  tasks:
    - include: tasks/tools.yml
    - include: tasks/services.yml

  vars:
    ntp_install: True
    ntp_use_intra: False
    load_sysctl_conf: True
    enable_iptables: False

  roles:
    - ansible-repo
    - ansible-ntp
    - ansible-optimize
