---
- hosts: "{{ hosts }}"
  become: yes
  become_method: sudo

  vars:
    limits_conf:
      - "80-nofile.conf"
      - "90-nproc.conf"
    load_sysctl_conf: true

  tasks:
    - include: tasks/limits.yml
    - include: tasks/sysctl.yml
