---

# copy centos yum repo
- name: yum | mkdir old repo backup dir
  file: path=/etc/yum.repos.d/bak state=directory mode=0755

- name: yum | test CentOS-Base.repo is exists
  stat: path=/etc/yum.repos.d/CentOS-Base.repo
  register: centos_base_repo

- name: yum | backup old centos repo
  shell: chdir=/etc/yum.repos.d mv -v CentOS-*.repo bak
  when: centos_base_repo.stat.exists == True

- name: yum | copy centos base repo
  copy: src=centos-base-6.repo dest=/etc/yum.repos.d/centos-base.repo owner=root group=root mode=644

# yum install epel-release

#- name: yum | yum install epel-release
#  yum: name=epel-release state=latest

- name: yum | import epel gpg key
  rpm_key: key=http://mirrors.ustc.edu.cn/epel/RPM-GPG-KEY-EPEL-6 state=present

- name: yum | yum install epel-release
  yum: name=epel-release state=latest


# copy epel yum repo
- name: yum | copy epel repo
  copy: src=epel-6.repo dest=/etc/yum.repos.d/epel.repo owner=root group=root mode=644

- name: yum | copy epel testing repo
  copy: src=epel-testing-6.repo dest=/etc/yum.repos.d/epel-testing.repo owner=root group=root mode=644
