---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_dependencies.
  set_fact:
    php_dependencies: "{{ __php_dependencies | list }}"
  when: php_dependencies is not defined

- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Define php_conf_path.
  set_fact:
    php_conf_path: "{{ __php_conf_path }}"
  when: php_conf_path is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: (php_install_from_source == false) and (ansible_os_family == 'RedHat')

# Install PHP from source when php_install_from_source is true.
#- include: install-from-source.yml
#  when: php_install_from_source == true

# Configure PHP.
- include: configure.yml
