---

- name: salt | add salt master ip config
  lineinfile: "dest=/etc/salt/minion regexp='^#master:.*' line='master: {{ salt_master_ip }}'"

- name: salt | add salt minion id config
  lineinfile: dest=/etc/salt/minion_id create=yes line={{ salt_minion_id }}

- name: salt | enable salt minion
  service: name=salt-minion enabled=yes

- name: salt | start salt minion
  service: name=salt-minion state=started
