---
- hosts: "{{ hosts }}"
  become: yes
  become_method: sudo

  vars:
    lan_interface: "eth0"
    lan_gateway: "10.1.172.254"
    private_network:
      - "10.0.0.0/8"
      - "192.168.0.0/16"
    use_network_scripts: true

  tasks:
    - include: tasks/main.yml
