---
- name: 拷贝Megacli到被管理机上
  copy: src={{ item }}     dest=/srv/
  with_items:
   - Lib_Utils-1.00-09.noarch.rpm
   - MegaCli-8.00.48-1.i386.rpm

- name: 安装MegaCli
  shell: rpm -ivh /srv/MegaCli-8.00.48-1.i386.rpm /srv/Lib_Utils-1.00-09.noarch.rpm 
  ignore_errors: True
  
   
- name: 将MegaCli命令加入到PATH环境变量中
  shell: echo 'export PATH=$PATH:/opt/MegaRAID/MegaCli/' > /etc/profile.d/megacli.sh  
