---

- name: install denpendencies required to setup a new version of keepavlied
  yum: pkg={{ item }} state=latest
  with_items:
    - gcc
    - gcc-c++ 
    - cmake
    - libnl*  
    - libpopt*
    - popt-static
    - openssl-devel
    - ncurses-devel
    - bison
    - libaio-devel
    - ipvsadm

### install keepavlied

- name: copy keepavlied  to client
  copy: src=/root/ansible-keepalived/files/keepalived-1.2.19.tar.gz  dest=/tmp/keepalived-1.2.19.tar.gz

- name: Ensure keepalived  is extracted
  shell: chdir=/tmp/ tar xvf keepalived-1.2.19.tar.gz  -C /tmp/

- name: Ensure keepalived  is configured
  shell: chdir=/tmp/keepalived-1.2.19  ./configure --prefix=/usr/local/keepalived


- name: Ensure keepavlied  make
  shell: chdir=/tmp/keepalived-1.2.19  make

- name: Ensure keepavlied  make install
  shell: chdir=/tmp/keepalived-1.2.19  make install


### configure keepalived

- name: copy init.d to /etc/init.d/
  shell: /bin/cp /usr/local/keepalived/etc/rc.d/init.d/keepalived /etc/init.d/

- name: copy to sysconfig
  shell: /bin/cp /usr/local/keepalived/etc/sysconfig/keepalived /etc/sysconfig/

- name: create keepalived dir
  shell: mkdir -pv /etc/keepalived

#- name: copy keepalived.conf 
  #shell: /bin/cp /usr/local/keepalived/etc/keepalived/keepalived.conf /etc/keepalived/

- name: copy to sbin
  shell: /bin/cp /usr/local/keepalived/sbin/keepalived /usr/sbin/

#- name: start to keepalived 
#  shell: /etc/init.d/keepalived start

